# Generated by Django 4.0 on 2021-12-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrappeduser',
            old_name='email',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='scrappeduser',
            old_name='location',
            new_name='notes',
        ),
    ]
